### ISSUE TITLE
Threat Hunting subnet issue

### ISSUE THREAD

**Issue by j0ebeer** [noodlemctwoodle/pf-azure-sentinel#12]
How do you permanently set the subnets & thresholds fields?  I've changed them to reflect my subnets and saved them but when I hit refresh it uses the default nets.
![Screen Shot 2021-08-05 at 11 07 42 AM](https://user-images.githubusercontent.com/60367983/128399878-1a7fcb88-23e7-4a11-a75f-cbf50ba489d3.png)
![Screen Shot 2021-08-05 at 11 05 25 AM](https://user-images.githubusercontent.com/60367983/128399880-cce10f99-a55a-482e-9c09-ad245ec5938f.png)

**Comment by noodlemctwoodle** [comment]
@j0ebeer 

First of nice car!!

You'll need to edit the workbook to set it permanently.

I am working on a Solution for Sentinel which should make the deployment a bit easier 🤗
